config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  devise_for :users
  resources :lists

  resources :lists do
    resources :artists
  end

  resources :artists do
    resources :songs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :list
  has_many :songs
end

app/models/list.rb
class List < ApplicationRecord
  has_many :artists
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_list
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
    
  def index
    @artists = @list.artists
  end

  def show
  end

  def new
    @artist = @list.artists.new
  end

  def edit 
  end

  def create
    @artist = @list.artists.new(artist_params)

    if @artist.save
      redirect_to [@list, @artist]
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@list, @artist]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to list_artists_path
  end

  private
    def set_list
      @list = List.find(params[:list_id])
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :avatar)
    end
  end 

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :update, :edit, :destroy]

  def index
    @lists = current_user.lists
    #@lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = current_user.lists.new(list_params)
    
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  
  def index
    @songs = @artist.songs
   
  end

  def new
    @song = Song.new

    render partial: "form"
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to list_artist_path(@artist.list_id, @artist)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to [@artist, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_song_path(@song)
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name, :song_id)
    end
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_with(model: [@list, @artist], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :avatar %>
  <%= f.text_field :avatar, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", list: @list, artist: @artist %>

<%= link_to "Back", list_artist_path(@list) %>

app/views/artists/index.html.erb
<h1>Artists</h1>
<%= link_to 'Add Artist', new_list_artist_path(@list) %> |
<%= link_to "Back to Billboards", lists_path%>
<hr />


<div class="ui grid">
  <% @artists.each do |artist| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://robohash.org/<%= artist.avatar %>?set=4" />
        </div>
        <div class="content">
          <div class="extra content">
            <div class="ui button">
    <li><%= link_to artist.name, [@list, artist] %></li>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/artists/new.html.erb
<%= render "form", list: @list, artist: @artist %>

<%= link_to "Back", list_artists_path(@list) %>

app/views/artists/show.html.erb
<h1><%= @list.name %></h1>
<h4>Name: <%= @artist.name %></h4>
<br />
<%= link_to 'View Songs', artist_songs_path(@artist) %> |
<%= link_to 'Edit Artist', edit_list_artist_path([@list, @artist]) %> |
<%= link_to 'Delete Artist', [@list, @artist], method: :delete %> |
<%= link_to 'Back To Artists', list_artists_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render "form", list: @list %>

<%= link_to "Show", list_path(@list) %> |
<%= link_to "Back", lists_path %>

app/views/lists/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h1 class="ui header">Top Music Categories</h1>
<hr />
<% @lists.each do |list| %>
  <h1><%= list.name %></h1>
  <%= link_to "Show Artists", list_artists_path(list) %> |
  <%= link_to "Edit", edit_list_path(list) %> |
  <%= link_to "Delete", list_path(list), method: :delete %>
<% end %>
<br />
<br />
<hr />
<%= link_to "New Category", new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form", list: @list %>

<%= link_to "Back", lists_path %>

app/views/lists/show.html.erb
<div class="ui card">
  <div class="content">
    <p class="header">
      <%= @list.name %> 
    </p>
  </div>
  <div class="extra content">
    <%= link_to 'Edit', edit_list_path(@list) %> |
    <%= link_to 'Back', lists_path %> |
    <%= link_to 'View Artists', list_artists_path(@list)%>

  </div>
</div>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_with(model: [@artist, @song], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

<%= link_to "Back", artist_songs_path(@artist) %>

app/views/songs/edit.html.erb
<%= render "form", song: @song %>

app/views/songs/index.html.erb
<h1>Songs</h1>
<%= link_to 'Add Song', new_artist_song_path(@artist) %>
<hr />
<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.name, [@artist, song] %></li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render "form", artist: @artist, song: @song %>

<%= link_to "Back", artist_songs_path(@artist) %>

app/views/songs/show.html.erb
<h1><%= @artist.name %></h1>
<h4>Name: <%= @song.name %></h4>
<br />
<br />
<%= link_to 'Edit Song', edit_artist_song_path([@artist, @song]) %> |
<%= link_to 'Delete Song', [@artist, @song], method: :delete %> |
<%= link_to 'Back To Artists', artist_songs_path(@artist) %>